# Generated by Django 3.0.8 on 2020-08-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
    ]
