# Generated by Django 3.0.8 on 2020-08-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0002_auto_20200806_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
