# Generated by Django 3.0.8 on 2020-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0005_track_outputtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='OutputType',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
