# Generated by Django 3.0.8 on 2020-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0006_auto_20200807_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='NStems',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
