# Generated by Django 3.0.8 on 2020-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0007_track_nstems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='audio',
        ),
        migrations.AddField(
            model_name='track',
            name='YTLink',
            field=models.URLField(null=True),
        ),
    ]
