# Generated by Django 3.0.8 on 2020-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0009_track_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='YTLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
