# Generated by Django 3.0.8 on 2020-08-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0010_auto_20200808_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='YTLink',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
    ]
