# Generated by Django 3.0.8 on 2020-08-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0012_auto_20200825_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='NStems',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='OutputType',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
