# Generated by Django 3.0.8 on 2020-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0014_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='Message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
