# Generated by Django 3.0.8 on 2020-09-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0015_auto_20200914_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='DateTimeAdded',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='DateTimeAdded',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='Message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
