# Generated by Django 3.0.8 on 2020-09-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0016_auto_20200914_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200, null=True)),
                ('Answer', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
